'------------------------------------------------------------------------------
' <auto-generated>
'     Bu kod araç tarafından oluşturuldu.
'     Çalışma Zamanı Sürümü:4.0.30319.42000
'
'     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
'     kod yeniden oluşturulursa kaybolur.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    'sınıfı tarafından otomatik olarak oluşturuldu.
    'Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    'komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    '''<summary>
    '''  Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("hastaneotomasyonu.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        '''  CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property _258916_arma_logo_turkce_jpg_1202jpg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("258916,arma-logo-turkce-jpg-1202jpg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property _258916_arma_logo_turkce_jpg_1202jpg1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("258916,arma-logo-turkce-jpg-1202jpg1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property _258916_arma_logo_turkce_jpg_1202jpg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("258916,arma-logo-turkce-jpg-1202jpg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property _5152_jpg_wh300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5152.jpg_wh300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property _51521() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("51521", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property _59640480_2399477246750569_6389279248875520000_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("59640480_2399477246750569_6389279248875520000_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property _63() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("63", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property cartoon_doctor_character_isolated_white_background_flat_style_vector_illustration_veterinarian_man_stethoscope_cute_design_222181539() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartoon-doctor-character-isolated-white-background-flat-style-vector-illustration"& _ 
                        "-veterinarian-man-stethoscope-cute-design-222181539", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property cartoon_doctor_character_isolated_white_background_flat_style_vector_illustration_veterinarian_man_stethoscope_cute_design_2221815391() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartoon-doctor-character-isolated-white-background-flat-style-vector-illustration"& _ 
                        "-veterinarian-man-stethoscope-cute-design-2221815391", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property Ekran_görüntüsü_2022_05_15_175546() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ekran görüntüsü 2022-05-15 175546", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property Ekran_görüntüsü_2022_05_15_1755461() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ekran görüntüsü 2022-05-15 1755461", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property geri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("geri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property kalpaile2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kalpaile2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property male_female_portrait_medical_doctor_flat_design_profile_icon_vector_illustration_209843799() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("male-female-portrait-medical-doctor-flat-design-profile-icon-vector-illustration-"& _ 
                        "209843799", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property memorial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("memorial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        '''</summary>
        Friend ReadOnly Property zyro_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zyro-image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
